export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source $HOME/.cargo/env

# Special variables
export TMPDIR=~/tmp
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/Development/local_llm/llama.cpp/build/bin
export N_PREFIX=$HOME/.js/n
export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig

# Update paths
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/dots/scripts
export PATH=$PATH:$HOME/Development/byte_blade/bin
export PATH=$PATH:$HOME/.local/psql/bin
export PATH=$PATH:$HOME/.local/nginx/sbin
export PATH=$PATH:$HOME/Development/builds/zig-linux-x86_64-0.14.0-dev.1057+76f062690 # Zig
export PATH=$PATH:$HOME/Development/builds/nvim-linux64/bin
export PATH=$PATH:$HOME/.js/npm/bin
export PATH=$HOME/.js/n/bin:$PATH
export PATH=$PATH:/$HOME/Development/builds/apache-jmeter-5.6.3/bin
export PATH=$PATH:$HOME/Development/local_llm/llama.cpp/build/bin

# Go
export GOPATH=$HOME/go 
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
export PATH=$PATH:~/.local/go/bin
export CGO_ENABLED=1

# ZOxide
eval "$(zoxide init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote.authenticate=false"

# My favorite docker ps
alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.Names}}\t{{.CreatedAt}}\t{{.Status}}"'

alias t="todo.sh"
